#%RAML 1.0 NamedExample
properties:
      addressId: "1"
      customerId: "1"
      address:
        houseNumber: "78844"
        street: 23 cambridge
        city: cambridge
        pincode: "02140"
        addressType: 'delivery'