#%RAML 1.0 NamedExample
value:
    firstName: Solomon
    lastName: Shawul
    email:    soloswalo@gmail.com 
    phone: "6178037280"
    address:
        houseNumber: "44 cambridgepark dr"
        street: 23 cambridge
        city: cambridge
        pincode: "02140"
        addressType: 'delivery'
        

