#%RAML 1.0
title: swiggy-customers-sapi-app

baseUri: http://localhost:8081
mediaType: application/json

types:
 Address: !include /datatype/Address.raml
 CustomerRequest: !include /datatype/CustomerRequest.raml
 errorMessage: !include /datatype/errormessage.raml 
 Customer: !include /datatype/customer.raml
 addressRequest: !include /datatype/addressRequest.raml
 Updatecustomer: !include /datatype/updatecustomer.raml
 
resourceTypes:
 collection: !include /resource/collection.raml
 member: !include /resource/member.raml

traits:
  Pageable: !include traits/pageable.raml
  
/customers:
  type: collection
  post:
  get: 
   is: [Pageable]
   responses:
     200:
       body:
         application/json:
           type: Customer[]

  /{id}:
    type: member
    get:  
    put:
     responses:
      200:
        body: Updatecustomer
         
    /addresses:
      type:
        collection
      post:
          
     





         
        

