#%RAML 1.0 DataType
properties:
    firstName: string
    lastName:  string
    email: string
    phone: number
    Address?:
        type: array
        items: !include Address.raml
example: !include ../example/address.raml         